name: Yadxy Cron Jobs

on:
  schedule:
    # Monthly fees (5:51 PM IST)
    - cron: "25 22 * * *"
    # Fee reminder (5:52 PM IST)
    - cron: "28 22 * * *"
    # Plan downgrade (4:26 PM IST)
    - cron: "56 10 * * *"

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Run Cron Job
        run: |
          curl -X POST https://api.yadxy.com/api/v1/cron/run \
          -H "Content-Type: application/json" \
          -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
          -d '{"job":"monthly-fees"}'
